[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[project]
name = "cse355-machine-design"
version = "0.3.0"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "render-html>=1.0.1",
    "typeguard>=4.6.0",
]
requires-python = ">=3.13"
authors = [
    {name = "Joshua J. Daymude", email = "jdaymude@asu.edu"},
    {name = "Saajan Maslanka", email = "academia@saajanm.com"},
]
maintainers = [
    {name = "Joshua J. Daymude", email = "jdaymude@asu.edu"},
]
description = "Rust and Python library supporting ASU's CSE 355 in the declaration, simulation, and visualization of Sipser-compatible automata"
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
keywords = ["automata", "sipser", "theoretical computer science", "turing machine"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Education",
]

[project.urls]
repository = "https://github.com/DaymudeLab/CSE355-MachineDesign"
issues = "https://github.com/DaymudeLab/CSE355-MachineDesign/issues"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
]
