[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "cse355-machine-design"
dynamic = ["version", "license"]  # Read from Cargo.toml.
description = "Rust and Python library supporting ASU's CSE 355 in the declaration, simulation, and visualization of Sipser-compatible automata"
readme = "python/README.md"
requires-python = ">=3.10"
authors = [
  {name = "Joshua Daymude", email = "jdaymude@asu.edu"},
  {name = "Saajan Maslanka", email = "sdmaslan@asu.edu"},
]
maintainers = [
  {name = "Joshua Daymude", email = "jdaymude@asu.edu"},
]

[project.urls]
Repository = "https://github.com/DaymudeLab/CSE355-MachineDesign"
Documentation = "https://docs.rs/cse355-machine-design/latest/cse355_machine_design/python"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source   = "python"
python-packages = ["cse355_machine_design"]

[pytest]
testpaths = "python/tests"
